-- ===========================================================================
-- LESSONS — MPM2D
-- ===========================================================================
--
-- GENERATED by tools/import_lessons.py. Two sources, one code path:
--   * Dileep Kumar's topicmindmap repository, remapped onto our units and
--     misconception tags (the MAP table in that script)
--   * lessons authored here to cover the subtopics his set does not reach
-- Edit the script and its sources, never this file.
--
-- 219 lessons. Every one is keyed to a misconception tag from our own question
-- bank, so the Improve section and a finished test can both link a weak
-- subtopic to the lesson that covers it. Every subtopic in the bank has one:
-- a student can never be told to revise something with nothing to read.
--
-- Bodies are markdown with two extensions, both produced by the importer:
--
--   :::img <name>     a diagram. Two PNGs exist per name, <name>_light.png
--   :::caption …      and <name>_dark.png, under web/figures/lessons/;
--   :::               Dart picks by Theme.of(context).brightness. Generated
--                     from inline SVG by tools/render_diagrams.py, which
--                     substitutes the theme palette for the colour tokens.
--
--   :::desmos <url>   an interactive graph, opened in a browser tab.
--   :::
--
-- Safe to re-run: the delete below clears the table and rebuilds it whole.
-- ===========================================================================

delete from lessons where course_code = 'MPM2D';

insert into lessons (course_code, unit, tag, sort_order, title, summary,
                     read_minutes, body, video_title, video_url, video_source)
values
($AMA$MPM2D$AMA$, $AMA$Analytic geometry$AMA$, $AMA$sub-geometry-applications$AMA$, 1, $AMA$Classifying Shapes$AMA$, $AMA$Coordinate geometry lets you prove what kind of shape you're looking at using nothing but arithmetic. Three tools do almost all the work: slope, length, and midpoint.$AMA$, 7, $AMA$# Classifying Shapes

## The Idea

Coordinate geometry lets you prove what kind of shape you're looking at using nothing but arithmetic — no protractor required. Three tools do almost all the work: **slope** (for angles and parallel/perpendicular sides), **length** (for equal sides), and **midpoint** (for bisected diagonals).

## The Toolkit

| Tool | What it proves |
|---|---|
| Slope | Parallel sides (equal slopes) or perpendicular sides (negative reciprocal slopes) |
| Length | Equal side lengths (using the distance formula) |
| Midpoint | Diagonals that bisect each other |

## Classifying Triangles

- **Scalene**: all three side lengths different.
- **Isosceles**: at least two side lengths equal.
- **Equilateral**: all three side lengths equal.
- **Right triangle**: two sides have slopes that are negative reciprocals (perpendicular), OR the side lengths satisfy the Pythagorean theorem.

## Classifying Quadrilaterals

- **Parallelogram**: both pairs of opposite sides have equal slopes (parallel).
- **Rectangle**: a parallelogram where adjacent sides are also perpendicular.
- **Rhombus**: a parallelogram where all four sides have equal length.
- **Square**: a rectangle AND a rhombus.

## Worked Example

Classify the quadrilateral with vertices `A(0, 0)`, `B(4, 0)`, `C(4, 3)`, `D(0, 3)`.

**Slopes of opposite sides**:
```
AB: (0-0)/(4-0) = 0          CD: (3-3)/(0-4) = 0        → AB ∥ CD
BC: (3-0)/(4-4) = undefined  DA: (0-3)/(0-0) = undefined → BC ∥ DA
```
Both pairs of opposite sides are parallel → **parallelogram**.

**Adjacent side slopes**: `AB` has slope `0` (horizontal), `BC` is undefined (vertical) → perpendicular → it's a **rectangle**.

**Side lengths**: `AB = 4`, `BC = 3` → not all equal → not a rhombus, so **it's a rectangle, not a square**.

:::img mpm2d-geometry-applications_1
:::

:::desmos https://www.desmos.com/calculator/kp9yzc9f4p
:::

## Common Mistakes

- Only checking one pair of sides instead of all the sides needed to fully classify the shape.
- Forgetting that "negative reciprocal" means both flip AND change sign (slope `2` is perpendicular to slope `-1/2`, not `1/2`).
- Concluding "parallelogram" from equal slopes without checking both pairs of opposite sides.

## Quick Gut-Check

Need parallel sides? Compare slopes. Need perpendicular sides? Check for negative reciprocal slopes. Need equal sides? Use the distance formula. Combine whichever checks the shape's definition requires.$AMA$, $AMA$Grade 10 Analytic Geometry: Classifying Figures on a Coordinate Grid$AMA$, $AMA$https://www.youtube.com/watch?v=uGevdVFatk0$AMA$, $AMA$Ms Havrot's Canadian University Math Prerequisites$AMA$),
($AMA$MPM2D$AMA$, $AMA$Analytic geometry$AMA$, $AMA$sub-midpoint-length$AMA$, 2, $AMA$Midpoint and Length of a Line Segment$AMA$, $AMA$Given two endpoints, you often need to find the point exactly halfway between them (midpoint) or the straight-line distance between them (length). Both formulas come straight from averaging coordinates and the Pythagorean theorem.$AMA$, 1, $AMA$# Midpoint and Length of a Line Segment

## The Idea

Given two endpoints, you often need to find the point exactly halfway between them (midpoint) or the straight-line distance between them (length). Both formulas come straight from averaging coordinates and the Pythagorean theorem.

## Midpoint Formula

The midpoint is just the **average** of the x-coordinates and the average of the y-coordinates:

```
M = ( (x₁ + x₂)/2 , (y₁ + y₂)/2 )
```

**Example**: Midpoint of (2, 3) and (8, 7):
```
M = ( (2+8)/2 , (3+7)/2 ) = (5, 5)
```

## Length (Distance) Formula

This comes from the Pythagorean theorem — imagine a right triangle formed between the two points:

```
d = √( (x₂ - x₁)² + (y₂ - y₁)² )
```

**Example**: Distance between (2, 3) and (8, 7):
```
d = √( (8-2)² + (7-3)² )
d = √( 36 + 16 )
d = √52 ≈ 7.2
```

:::img mpm2d-midpoint-length_0
:::

:::desmos https://www.desmos.com/calculator/qk41ytbhva
:::

## Worked Example: Both Together

Triangle vertices: A(0, 0), B(6, 0), C(3, 6).

Find the midpoint of AB and the length of AC.

**Midpoint of AB**: `M = ((0+6)/2, (0+0)/2) = (3, 0)`

**Length of AC**: `d = √((3-0)² + (6-0)²) = √(9+36) = √45 ≈ 6.7`

## Where This Shows Up

- Finding the centre of a line segment (e.g., a support beam, a road midpoint)
- Verifying triangle properties (e.g., is a triangle isosceles? Compare side lengths)
- Setting up circle equations, since radius = distance from centre to any point on the circle

## Common Mistakes

- Mixing up which point is `(x₁, y₁)` vs `(x₂, y₂)` — it doesn't matter which you call first, as long as you're consistent within one calculation.
- Forgetting to square root at the end of the distance formula (leaving the answer as the squared distance).

## Quick Gut-Check

Midpoint = average the coordinates. Length = Pythagorean theorem with the coordinate differences as the legs.$AMA$, $AMA$Midpoint & Length of a Line Segment | jensenmath.ca | grade 10 math$AMA$, $AMA$https://www.youtube.com/watch?v=vZZD43NlDwE$AMA$, $AMA$JensenMath$AMA$),
($AMA$MPM2D$AMA$, $AMA$Analytic geometry$AMA$, $AMA$sub-equation-of-circle$AMA$, 3, $AMA$Equation of a Circle (Centred at the Origin)$AMA$, $AMA$A circle is just the set of all points that are exactly the same distance (the radius) from one centre point. When the centre is at the origin (0, 0), that idea translates directly into a simple equation using the distance formula.$AMA$, 1, $AMA$# Equation of a Circle (Centred at the Origin)

## The Idea

A circle is just the set of all points that are exactly the same distance (the radius) from one centre point. When the centre is at the origin (0, 0), that idea translates directly into a simple equation using the distance formula.

## Building the Formula

If a point `(x, y)` is on a circle of radius `r` centred at `(0, 0)`, then its distance from the origin is `r`:

```
√(x² + y²) = r
```

Square both sides to remove the square root:

```
x² + y² = r²
```

That's it — the equation of a circle centred at the origin with radius `r`.

## Reading the Equation

- Given the equation, the radius is the **square root of the number on the right**.
- Given the radius, just square it and write the equation.

## Worked Examples

**Find the radius**: `x² + y² = 49` → `r = √49 = 7`

**Write the equation** for a circle with radius 5: `x² + y² = 25`

**Is a point on the circle?** Is (3, 4) on `x² + y² = 25`?
```
3² + 4² = 9 + 16 = 25 ✓
```
Yes — it's on the circle.

:::img mpm2d-equation-of-circle_0
:::

:::desmos https://www.desmos.com/calculator/r2oaou9fqj
:::

## Sketching It

Once you know `r`, mark points `r` units up, down, left, and right from the origin — `(r, 0)`, `(-r, 0)`, `(0, r)`, `(0, -r)` — then sketch a smooth circle through them.

## Common Mistakes

- Forgetting to square the radius when writing the equation (writing `x² + y² = 5` instead of `x² + y² = 25`).
- Forgetting to square root when finding the radius from the equation.

## Quick Gut-Check

`x² + y² = r²` — the number on the right is always the radius **squared**, not the radius itself.$AMA$, $AMA$Equation of a Circle | grade 10 | jensenmath.ca$AMA$, $AMA$https://www.youtube.com/watch?v=XrYqueB01aQ$AMA$, $AMA$JensenMath$AMA$),
($AMA$MPM2D$AMA$, $AMA$Analytic geometry$AMA$, $AMA$sub-median-bisector-altitude$AMA$, 4, $AMA$Parallel and Perpendicular Lines$AMA$, $AMA$Slope tells you everything about how two lines relate to each other. Parallel lines never meet because they point in exactly the same direction; perpendicular lines cross at a perfect right angle. Both relationships come down to comparing slopes.$AMA$, 1, $AMA$# Parallel and Perpendicular Lines

## The Idea

Slope tells you everything about how two lines relate to each other. Parallel lines never meet because they point in exactly the same direction; perpendicular lines cross at a perfect right angle. Both relationships come down to comparing slopes.

## The Two Rules

- **Parallel lines** have the **same slope**: `m₁ = m₂`
- **Perpendicular lines** have slopes that are **negative reciprocals**: `m₁ = -1/m₂` (flip the fraction and switch the sign)

## Worked Example: Parallel

Find the equation of a line parallel to `y = 3x + 2` that passes through `(1, 5)`.

Parallel means same slope: `m = 3`. Use point-slope form:
```
y - 5 = 3(x - 1)
y - 5 = 3x - 3
y = 3x + 2 ... wait, simplify carefully:
y = 3x - 3 + 5
y = 3x + 2
```
Since that matches the original line exactly, double-check the point isn't actually on the original line. (In practice, always verify your point isn't already on the given line, or you'd get the same line back instead of a new parallel one.)

## Worked Example: Perpendicular

Find the slope of a line perpendicular to a line with slope `2/3`.

Flip it: `3/2`. Switch the sign: **`-3/2`**

So if the original line is `y = (2/3)x + 1`, any perpendicular line has slope `-3/2`, e.g., `y = (-3/2)x + 4`.

:::img mpm2d-median-bisector-altitude_0
:::

:::desmos https://www.desmos.com/calculator/yaq5brom5g
:::

## Quick Slope Reference

| Original slope | Parallel slope | Perpendicular slope |
|---|---|---|
| 4 | 4 | -1/4 |
| -2/5 | -2/5 | 5/2 |
| 1 | 1 | -1 |

## Common Mistakes

- Forgetting to **flip** the fraction for perpendicular slopes, only switching the sign.
- Forgetting to switch the **sign** for perpendicular slopes, only flipping the fraction.
- Mixing up which rule applies — parallel keeps the slope identical, perpendicular changes it completely.

## Quick Gut-Check

Same slope = parallel. Flip and negate the slope = perpendicular.$AMA$, $AMA$Equations of parallel and perpendicular lines | Analytic geometry | Geometry$AMA$, $AMA$https://www.youtube.com/watch?v=9hryH94KFJA$AMA$, $AMA$Khan Academy$AMA$),
($AMA$MPM2D$AMA$, $AMA$Analytic geometry$AMA$, $AMA$sub-geometry-applications$AMA$, 5, $AMA$Verifying Geometric Properties Using Analytic Geometry$AMA$, $AMA$Instead of a protractor and ruler, you can prove facts about shapes — "this triangle is isosceles," "this quadrilateral is a rectangle," "these diagonals bisect each other" — using nothing but coordinates and the formulas you already know: slope, distance, and midpoint.$AMA$, 2, $AMA$# Verifying Geometric Properties Using Analytic Geometry

## The Idea

Instead of a protractor and ruler, you can prove facts about shapes — "this triangle is isosceles," "this quadrilateral is a rectangle," "these diagonals bisect each other" — using nothing but coordinates and the formulas you already know: slope, distance, and midpoint.

## Your Toolkit

- **Slope** → proves lines are parallel (equal slopes) or perpendicular (negative reciprocal slopes)
- **Distance formula** → proves sides are equal length (e.g., isosceles or equilateral triangles)
- **Midpoint formula** → proves segments bisect each other, or finds the midpoint of a side

## Worked Example: Is This Triangle Isosceles?

Triangle A(0, 0), B(4, 0), C(2, 5). Check if any two sides are equal length.

```
AB = √((4-0)² + (0-0)²) = √16 = 4
AC = √((2-0)² + (5-0)²) = √(4+25) = √29
BC = √((2-4)² + (5-0)²) = √(4+25) = √29
```

Since **AC = BC**, the triangle is **isosceles**.

:::img mpm2d-geometry-applications_0
:::

:::desmos https://www.desmos.com/calculator/nnx1rlb7ua
:::

## Worked Example: Do Diagonals Bisect Each Other?

Rectangle vertices: A(0, 0), B(4, 0), C(4, 3), D(0, 3). Do diagonals AC and BD share the same midpoint?

```
Midpoint of AC = ((0+4)/2, (0+3)/2) = (2, 1.5)
Midpoint of BD = ((4+0)/2, (0+3)/2) = (2, 1.5)
```

Same point — the diagonals **bisect each other**, confirming a key rectangle property.

## The General Strategy

1. **Identify what property you're proving** (equal sides? parallel sides? right angle? bisecting diagonals?).
2. **Pick the matching formula** (distance, slope, or midpoint).
3. **Calculate for each relevant pair** of points.
4. **Compare results** and state your conclusion clearly.

## Common Mistakes

- Choosing the wrong formula for the property (e.g., using distance when the question is really about parallel sides — that needs slope).
- Doing the calculation but forgetting to state the conclusion in words ("therefore, triangle ABC is isosceles").

## Quick Gut-Check

Equal lengths → distance formula. Same direction or right angle → slope. Halfway point → midpoint formula.$AMA$, $AMA$Grade 10 Analytic Geometry: Verifying Properties of Geometric Figures$AMA$, $AMA$https://www.youtube.com/watch?v=3V7PDJP_bPM$AMA$, $AMA$Ms Havrot's Canadian University Math Prerequisites$AMA$),
($AMA$MPM2D$AMA$, $AMA$Factoring$AMA$, $AMA$sub-multiplying-binomials$AMA$, 1, $AMA$Expanding and Simplifying Polynomial Expressions$AMA$, $AMA$Expanding means removing brackets by multiplying everything out, then combining any like terms. It's the reverse of factoring — you'll use it constantly to convert between forms of a quadratic.$AMA$, 1, $AMA$# Expanding and Simplifying Polynomial Expressions

## The Idea

Expanding means removing brackets by multiplying everything out, then combining any like terms. It's the reverse of factoring — you'll use it constantly to convert between forms of a quadratic.

## The Tool: FOIL

For two binomials, multiply **F**irst, **O**uter, **I**nner, **L**ast terms, then add them up.

```
(x + 3)(x + 5)
```

- First: `x · x = x²`
- Outer: `x · 5 = 5x`
- Inner: `3 · x = 3x`
- Last: `3 · 5 = 15`

Add them: `x² + 5x + 3x + 15 = x² + 8x + 15`

:::img mpm2d-multiplying-binomials_0
:::

:::desmos https://www.desmos.com/calculator/tb3sxtfys6
:::

## Squaring a Binomial

`(2x + 5)²` means `(2x + 5)(2x + 5)` — don't skip straight to squaring each term separately, that's a classic trap.

```
(2x + 5)(2x + 5)
= 4x² + 10x + 10x + 25
= 4x² + 20x + 25
```

## Worked Example

Expand `(2x - y)(x + 3y)`:
- First: `2x · x = 2x²`
- Outer: `2x · 3y = 6xy`
- Inner: `-y · x = -xy`
- Last: `-y · 3y = -3y²`

Combine: `2x² + 6xy - xy - 3y² = 2x² + 5xy - 3y²`

## Common Mistakes

- **Squaring shortcut error**: `(x + a)² ≠ x² + a²` — you must expand fully; the middle term is easy to forget.
- **Sign slips**: a negative sign outside brackets (like `-y`) applies to every term it multiplies.
- **Not combining like terms** at the end — always simplify as far as possible.

## Quick Gut-Check

If you see two sets of brackets multiplied together, FOIL it, then scan for like terms to combine. That's 90% of expanding.$AMA$, $AMA$How to Expand and Simplify Polynomials, Distributive Property, FOIL (Grade 10 Academic)$AMA$, $AMA$https://www.youtube.com/watch?v=dKG_bRyGRNM$AMA$, $AMA$How to Learn$AMA$),
($AMA$MPM2D$AMA$, $AMA$Factoring$AMA$, $AMA$sub-common-factoring$AMA$, 2, $AMA$Factoring Polynomials$AMA$, $AMA$Factoring is the reverse of expanding — turning a spread-out expression back into brackets multiplied together. It's the key skill for solving quadratic equations, so it's worth getting fast at spotting which method to use.$AMA$, 1, $AMA$# Factoring Polynomials

## The Idea

Factoring is the reverse of expanding — turning a spread-out expression back into brackets multiplied together. It's the key skill for solving quadratic equations, so it's worth getting fast at spotting which method to use.

## Method 1: Common Factor (Always Check This First)

Look for a number and/or variable in every term.

```
2x² + 4x = 2x(x + 2)
```

## Method 2: Factoring Trinomials (x² + bx + c)

Find two numbers that **multiply to c** and **add to b**.

```
x² - x - 6
```
Need two numbers that multiply to -6 and add to -1 → **3 and -2**

```
x² - x - 6 = (x + 3)(x - 2)
```

:::img mpm2d-common-factoring_0
:::

:::desmos https://www.desmos.com/calculator/ujqqrsazjx
:::

## Method 3: Difference of Squares

Whenever you see `(something)² - (something else)²`:

```
4x² - 25 = (2x)² - (5)² = (2x - 5)(2x + 5)
```

## Method 4: Factor by Grouping (4 terms)

Split into two pairs, factor each pair, then factor out the common bracket.

```
2x - 2y + ax - ay
= 2(x - y) + a(x - y)
= (x - y)(2 + a)
```

## The Big Connection

The factors of a quadratic tell you the **x-intercepts** (zeros) of its graph. If `y = a(x - r)(x - s)`, the parabola crosses the x-axis exactly at `x = r` and `x = s`.

## Common Mistakes

- Skipping the common-factor check first — it makes everything else easier.
- Sign errors when finding the two numbers for trinomials.
- Trying to force difference-of-squares on something that isn't actually a difference of two squares.

## Quick Gut-Check

Count the terms: 2 terms → check difference of squares. 3 terms → look for common factor, then trinomial factoring. 4 terms → try grouping.$AMA$, $AMA$Factoring Quadratics x^2+bx+c (full lesson) | math 10 | jensenmath.ca$AMA$, $AMA$https://www.youtube.com/watch?v=n-GVDng5p9g$AMA$, $AMA$JensenMath$AMA$),
($AMA$MPM2D$AMA$, $AMA$Factoring$AMA$, $AMA$sub-factoring-complex-trinomials$AMA$, 3, $AMA$Factoring ax² + bx + c$AMA$, $AMA$When the x² term has a coefficient other than 1, you split the middle term into two pieces that multiply to a × c and add to b, then factor the four terms in pairs.$AMA$, 3, $AMA$# Factoring ax² + bx + c

## The Idea

When the `x²` term carries a coefficient other than 1, the old trick — two numbers that multiply to `c` and add to `b` — stops working on its own. The fix is to notice that the middle term is really two smaller `x` terms that were added together at some point, like a bill that was split between two people. Pull it back apart and the expression falls into two easy pairs. The method is called **decomposition**.

## The Method

For `ax² + bx + c`:

- Factor out any common factor from all three terms first.
- Find two numbers that multiply to `a × c` and add to `b`.
- Split the middle term into those two `x` terms.
- Group the four terms into two pairs and common-factor each pair.
- The identical bracket that appears in both pairs comes out front.

```
ax² + bx + c   →   ax² + (m)x + (n)x + c   where   m × n = a × c   and   m + n = b
```

The product to aim for is `a × c`, not `c` on its own. That single change is the whole difference from the simple case.

## Worked Example

Factor `3x² + 10x + 8`.

- `a × c = 3 × 8 = 24`, and `b = 10`.
- Two numbers multiplying to 24 and adding to 10: **6 and 4**.
- Split the middle term: `3x² + 6x + 4x + 8`
- Group: `(3x² + 6x) + (4x + 8)`
- Common-factor each pair: `3x(x + 2) + 4(x + 2)`
- Both pairs share `(x + 2)`, so: `(x + 2)(3x + 4)`

Expanding back gives `3x² + 4x + 6x + 8 = 3x² + 10x + 8`, so it checks out.

:::img mpm2d-factoring-complex-trinomials_0
:::caption The two numbers you hunt for multiply to a × c and add to b; they are the split of the middle term, not the contents of the brackets.
:::

## Common Mistakes

- **Hunting for a product of `c` instead of `a × c`.** For `3x² + 10x + 8`, looking for two numbers that multiply to 8 and add to 10 finds nothing, and the usual conclusion is "it doesn't factor". The target product is 24, and 6 and 4 work fine.
- **Putting the two numbers straight into the brackets.** Having found 6 and 4, writing `(x + 6)(x + 4)` ignores the `3`. Those numbers split the middle term; they are not the contents of the brackets.
- **Stopping after the split.** `3x² + 6x + 4x + 8` is the same expression rewritten, not a factored one. You are finished only when the answer is brackets multiplied together.
- **Losing a sign when grouping.** In `2x² - 7x + 3`, the split is `2x² - 6x - x + 3`, and the second pair must be factored as `-1(x - 3)`, giving `(x - 3)(2x - 1)`. Factoring it as `+1(x - 3)` or `-1(x + 3)` breaks the match with the first bracket.
- **Skipping the common factor.** `6x² + 15x + 6` sends you looking for a product of 36; take out the 3 first and you only have to factor `2x² + 5x + 2`.

## Quick Gut-Check

Multiply to `a × c`, add to `b`, split, group. If the two brackets after grouping aren't identical, you have either got the signs wrong or need to swap the order of the two split terms.$AMA$, null, null, null),
($AMA$MPM2D$AMA$, $AMA$Factoring$AMA$, $AMA$sub-factoring-simple-trinomials$AMA$, 4, $AMA$Factoring x² + bx + c$AMA$, $AMA$Factoring a trinomial with a leading coefficient of 1 comes down to finding two numbers that multiply to the constant and add to the middle coefficient.$AMA$, 2, $AMA$# Factoring x² + bx + c

## The Idea

Expand `(x + m)(x + n)` and you get `x² + (m + n)x + mn`. Read that line backwards and the method appears on its own: to factor `x² + bx + c`, find two numbers that **multiply to `c`** and **add to `b`**. The search is always short, because the only candidates are the factor pairs of `c`.

```
x² + bx + c = (x + m)(x + n)   where   m × n = c   and   m + n = b
```

## Read the Signs First

The signs of `b` and `c` tell you what kind of pair you are looking for before you test a single number:

- `c` positive, `b` positive → both numbers positive.
- `c` positive, `b` negative → **both numbers negative**.
- `c` negative → one positive and one negative, and the number with the bigger size takes the sign of `b`.

## Worked Example

Factor `x² - 9x + 20`.

- `c = 20` is positive and `b = -9` is negative, so both numbers are negative.
- Factor pairs of 20: 1 and 20, 2 and 10, 4 and 5.
- With both negative, `-4` and `-5` multiply to 20 and add to `-9`.
- So `x² - 9x + 20 = (x - 4)(x - 5)`.
- Check the middle term: outer plus inner is `-5x - 4x = -9x`. Correct.

## When It Doesn't Factor

If you work through every factor pair of `c` and none of them adds to `b`, the trinomial does not factor over the integers. That is a genuine answer, not a failure — such a quadratic is solved with the quadratic formula instead.

## Common Mistakes

- **Swapping the two jobs**: looking for numbers that add to `c` and multiply to `b`. For `x² + 7x + 10` that means hunting for a pair that multiplies to 7 and adds to 10, finding none, and wrongly deciding the trinomial is unfactorable. It is `(x + 2)(x + 5)`.
- **Ignoring `b` when `c` is positive.** `x² - 7x + 12` is not `(x + 3)(x + 4)`. Both 3 and 4 must be negative to add to `-7`: `(x - 3)(x - 4)`.
- **Putting the minus on the wrong number when `c` is negative.** `x² - 3x - 10` is `(x + 2)(x - 5)`. Writing `(x - 2)(x + 5)` uses the same digits but produces a middle term of `+3x`.
- **Forgetting the common factor.** `2x² + 10x + 12` is not in `x² + bx + c` form at all. Take out the 2 first, factor `x² + 5x + 6`, and leave the 2 in the answer: `2(x + 2)(x + 3)`.
- **Never checking.** Multiplying the outer and inner terms of your answer takes five seconds and catches every sign slip.

## Quick Gut-Check

Multiply to the last number, add to the middle number. Then expand the outer and inner products in your head — they have to add to `bx`, or the answer is wrong.$AMA$, null, null, null),
($AMA$MPM2D$AMA$, $AMA$Factoring$AMA$, $AMA$sub-special-products$AMA$, 5, $AMA$Special Products$AMA$, $AMA$Perfect square trinomials and the difference of squares are the two patterns worth recognising on sight, in both directions — expanding and factoring.$AMA$, 2, $AMA$# Special Products

## The Idea

A few products turn up so often that it pays to recognise them on sight instead of expanding from scratch every time. They are the ones where the two brackets are almost the same: a binomial multiplied by itself, and a binomial multiplied by its own sign-flipped twin.

## The Three Patterns

```
(a + b)² = a² + 2ab + b²
(a - b)² = a² - 2ab + b²
(a + b)(a - b) = a² - b²
```

The first two are **perfect square trinomials**. The third is the **difference of squares**, and it is the only one where the middle terms disappear: `+ab` and `-ab` cancel, leaving just two terms.

:::img mpm2d-special-products_0
:::caption The two ab rectangles are the middle term; leaving them out is what turns (a + b)² into the wrong answer a² + b².
:::

## Running Them Backwards

The same patterns are how you factor on sight:

- **Two terms, both perfect squares, with a minus between them** → difference of squares. `9x² - 49 = (3x)² - 7² = (3x + 7)(3x - 7)`.
- **Three terms whose first and last are perfect squares, with a middle term equal to twice the product of their roots** → perfect square trinomial. `x² + 12x + 36 = (x + 6)²`, because `2 × x × 6 = 12x`.

## Worked Example

Expand `(4x - 3)²`.

- Here `a = 4x` and `b = 3`.
- `a² = (4x)² = 16x²`
- `2ab = 2 × 4x × 3 = 24x`, and the pattern for a difference carries a minus, so `-24x`
- `b² = 3² = 9`
- `(4x - 3)² = 16x² - 24x + 9`

The last term is `+9`, not `-9` — squaring `-3` makes it positive. Only the middle term feels the subtraction.

## Common Mistakes

- **Distributing the square across the sum.** Writing `(x + 5)² = x² + 25` skips the two `5x` products hiding in the middle. Squaring a bracket means multiplying it by itself, so the answer is `x² + 10x + 25`.
- **Flipping the sign of the last term.** In `(x - 5)²` the constant is `+25`, because `(-5)(-5)` is positive. Students who write `x² - 10x - 25` have changed one sign too many.
- **Forcing difference of squares onto a sum.** `x² + 9` does not factor. The pattern needs a subtraction; a sum of two squares has no factors over the integers.
- **Not testing the middle term against `2ab`.** `x² + 10x + 16` looks like a perfect square because 16 is a square, but `2 × x × 4 = 8x`, not `10x`. It is an ordinary trinomial: `(x + 2)(x + 8)`.
- **Missing a common factor first.** `8x² - 50` is not a difference of squares as it stands, since 8 and 50 are not perfect squares. Take out the 2: `2(4x² - 25) = 2(2x + 5)(2x - 5)`.

## Quick Gut-Check

Two terms, a minus, both perfect squares → `(a + b)(a - b)`. Three terms → check that the middle one is exactly `2ab` before you call it a perfect square.$AMA$, null, null, null),
($AMA$MPM2D$AMA$, $AMA$Linear systems$AMA$, $AMA$sub-elimination$AMA$, 1, $AMA$Solving Linear Systems by Elimination$AMA$, $AMA$Imagine you and a friend are trying to figure out the price of a burger and a drink, but neither of you knows both prices — you each just know a combo total. Elimination is the trick where you combine two equations so one of the unknowns *disappears*, leaving you with a single easy equation to solve.$AMA$, 2, $AMA$# Solving Linear Systems by Elimination

## The Idea

Imagine you and a friend are trying to figure out the price of a burger and a drink, but neither of you knows both prices — you each just know a combo total. Elimination is the trick where you combine two equations so one of the unknowns *disappears*, leaving you with a single easy equation to solve.

## When to Use It

Elimination works best when the equations are already in the form:

```
Ax + By = C
```

and one variable has matching (or easily matched) coefficients — meaning you can add or subtract the equations and have a variable cancel out.

## The Steps

1. **Line up** both equations, x-terms and y-terms stacked.
2. **Match the coefficients** of one variable (multiply one or both equations by a number so that variable has the same size coefficient, opposite or same sign).
3. **Add or subtract** the equations to eliminate that variable.
4. **Solve** the simple one-variable equation that's left.
5. **Substitute back** into either original equation to find the second variable.
6. **Check** your answer in both original equations.

## Worked Example

Solve:
```
2x + 3y = 12
4x - 3y = 6
```

The `y` terms already match (+3y and -3y) — that's a gift. Add the equations straight down:

```
2x + 3y = 12
4x - 3y =  6
-----------------
6x + 0  = 18
```

So `6x = 18`, meaning `x = 3`.

Substitute `x = 3` into the first equation:
```
2(3) + 3y = 12
6 + 3y = 12
3y = 6
y = 2
```

**Answer: x = 3, y = 2**

Quick check in equation 2: `4(3) - 3(2) = 12 - 6 = 6` ✓

:::img mpm2d-elimination_0
:::

:::desmos https://www.desmos.com/calculator/htz32xkgc6
:::

## What If Nothing Matches?

If no coefficients line up, multiply one or both equations so they do. For example, if you have `3x + 2y = 7` and `x - y = 1`, multiply the second equation by 2 to get `2x - 2y = 2`, and now the y-terms are ready to cancel when you add.

## Common Mistakes to Watch For

- **Sign errors**: subtracting equations means every term flips sign — easy to lose a negative.
- **Multiplying only one side**: whatever you multiply an equation by has to hit *every* term, not just the one you're targeting.
- **Forgetting to substitute back**: solving for one variable isn't the finish line — you need both x and y.

## Quick Gut-Check

Ask yourself: *"Which variable can I make cancel with the least amount of multiplying?"* That's usually your fastest path to the answer.$AMA$, $AMA$Solving Linear Systems Using ELIMINATION | math 10 | jensenmath.ca$AMA$, $AMA$https://www.youtube.com/watch?v=kuxX1m4X6vI$AMA$, $AMA$JensenMath$AMA$),
($AMA$MPM2D$AMA$, $AMA$Linear systems$AMA$, $AMA$sub-substitution$AMA$, 2, $AMA$Solving Linear Systems by Substitution$AMA$, $AMA$If one equation already tells you what a variable *equals* (or can easily be rearranged to), you can plug that expression directly into the other equation — swapping out a variable for its equivalent so only one unknown is left.$AMA$, 1, $AMA$# Solving Linear Systems by Substitution

## The Idea

If one equation already tells you what a variable *equals* (or can easily be rearranged to), you can plug that expression directly into the other equation — swapping out a variable for its equivalent so only one unknown is left.

## When to Use It

Substitution shines when one equation is already solved for a variable (like `y = 2x + 1`), or can be isolated in one easy step.

## The Steps

1. **Isolate** one variable in one equation (solve for x or y).
2. **Substitute** that expression into the *other* equation.
3. **Solve** the resulting one-variable equation.
4. **Substitute back** to find the second variable.
5. **Check** in both original equations.

## Worked Example

Solve:
```
y = 2x + 1
3x + y = 11
```

Equation 1 already gives us `y`. Substitute it into equation 2:
```
3x + (2x + 1) = 11
5x + 1 = 11
5x = 10
x = 2
```

Substitute `x = 2` back into `y = 2x + 1`:
```
y = 2(2) + 1 = 5
```

**Answer: x = 2, y = 5**

Check in equation 2: `3(2) + 5 = 6 + 5 = 11` ✓

:::img mpm2d-substitution_0
:::

:::desmos https://www.desmos.com/calculator/eubqiz9gka
:::

## If Neither Equation Is Pre-Solved

Solve `2x + y = 7` for `y` first: `y = 7 - 2x`, then substitute that into the other equation. Pick whichever variable isolates with the least fraction-hassle.

## Common Mistakes

- Substituting into the **same** equation you just isolated from (you'll get 0 = 0, which tells you nothing new) — always substitute into the *other* equation.
- Forgetting to use brackets around the substituted expression, which causes sign errors.
- Stopping after finding one variable — always go back for the second.

## Quick Gut-Check

See an equation already solved for x or y (or easy to isolate)? That's your signal to use substitution instead of elimination.$AMA$, $AMA$Solving Linear Systems Using SUBSTITUTION | Math10 | jensenmath.ca$AMA$, $AMA$https://www.youtube.com/watch?v=aaE5OwMYboM$AMA$, $AMA$JensenMath$AMA$),
($AMA$MPM2D$AMA$, $AMA$Linear systems$AMA$, $AMA$sub-solving-by-graphing$AMA$, 3, $AMA$Solving Linear Systems by Graphing$AMA$, $AMA$Every linear equation is a straight line. When you have two equations, their solution is simply the **point where the two lines cross** — because that's the one (x, y) point that satisfies both equations at once.$AMA$, 1, $AMA$# Solving Linear Systems by Graphing

## The Idea

Every linear equation is a straight line. When you have two equations, their solution is simply the **point where the two lines cross** — because that's the one (x, y) point that satisfies both equations at once.

## The Steps

1. **Graph both lines** (using slope-intercept form, a table of values, or intercepts).
2. **Find the intersection point** — read its coordinates directly off the graph.
3. **Check** by substituting that point into both original equations.

## Worked Example

Graph and solve:
```
y = x + 1
y = -x + 5
```

Line 1 (`y = x + 1`): starts at y-intercept 1, slope 1 — goes up 1, right 1.
Line 2 (`y = -x + 5`): starts at y-intercept 5, slope -1 — goes down 1, right 1.

Plotting both, they cross at **(2, 3)**.

Check: `y = 2 + 1 = 3` ✓ and `y = -2 + 5 = 3` ✓

**Answer: x = 2, y = 3**

:::img mpm2d-solving-by-graphing_0
:::

:::desmos https://www.desmos.com/calculator/mfjucosvni
:::

## The Three Possible Outcomes

- **Lines cross once** → exactly one solution (most common case).
- **Lines are parallel** (same slope, different y-intercept) → **no solution** — they never meet.
- **Lines are identical** (same slope and y-intercept) → **infinite solutions** — every point on the line works.

## Why Use Graphing At All?

It's the most visual way to *see* what "solving a system" actually means, and it's great for quickly estimating an answer or checking whether an algebraic answer makes sense. But it's less precise than substitution or elimination when the intersection isn't at nice whole-number coordinates.

## Common Mistakes

- Graphing carelessly and misreading the intersection point.
- Forgetting to check whether lines are parallel before assuming they'll cross somewhere.

## Quick Gut-Check

The solution to a linear system is always just "where do the lines meet?" — graphing makes that literal.$AMA$, $AMA$Solve a Linear System by Graphing | jensenmath.ca | grade 10$AMA$, $AMA$https://www.youtube.com/watch?v=OAOGF1lJN5E$AMA$, $AMA$JensenMath$AMA$),
($AMA$MPM2D$AMA$, $AMA$Linear systems$AMA$, $AMA$sub-linear-applications$AMA$, 4, $AMA$Applications of Linear Systems$AMA$, $AMA$Word problems involving two unknowns and two conditions are exactly what linear systems are built for. The hard part usually isn't the algebra — it's translating the words into two equations.$AMA$, 6, $AMA$# Applications of Linear Systems

## The Idea

Word problems involving two unknowns and two conditions are exactly what linear systems are built for. The hard part usually isn't the algebra — it's translating the words into two equations. Once you have those, substitution or elimination takes over.

## The Translation Process

1. **Identify the two unknowns** and give them variable names.
2. **Find two conditions** in the problem — each one becomes an equation.
3. **Solve the system** using substitution or elimination.
4. **Check your answer makes sense** in the context of the problem (no negative ages, no fractional people, etc.).

## Worked Example: Mixture Problem

A movie theatre sells adult tickets for $12 and child tickets for $8. One evening, 150 tickets were sold for a total of $1560. How many of each type were sold?

**Set up variables**: let `a` = number of adult tickets, `c` = number of child tickets.

**Two conditions**:
```
a + c = 150             (total tickets)
12a + 8c = 1560         (total revenue)
```

**Solve by substitution**: from the first equation, `c = 150 - a`. Substitute:
```
12a + 8(150 - a) = 1560
12a + 1200 - 8a = 1560
4a = 360
a = 90
```
Then `c = 150 - 90 = 60`.

**Answer**: 90 adult tickets and 60 child tickets.

**Check**: `90 + 60 = 150` ✓ and `12(90) + 8(60) = 1080 + 480 = 1560` ✓

## Worked Example: Speed Problem

A boat travels 24 km downstream in 2 hours, and the same 24 km upstream takes 3 hours. Find the boat's speed in still water and the current's speed.

Let `b` = boat's speed, `w` = current's speed.
```
Downstream: b + w = 24 ÷ 2 = 12
Upstream:   b - w = 24 ÷ 3 = 8
```
Add the equations to eliminate `w`:
```
2b = 20  →  b = 10
```
Substitute back: `10 + w = 12 → w = 2`.

**Answer**: boat speed = 10 km/h, current speed = 2 km/h.

:::img mpm2d-linear-applications_0
:::

:::desmos https://www.desmos.com/calculator/u0lkzkf7yz
:::

## Common Mistakes

- Writing only one equation instead of finding both conditions the problem gives you.
- Mixing up which quantity each variable represents partway through.
- Skipping the final "does this make sense" check — a negative number of tickets is a sign of an algebra slip.

## Quick Gut-Check

Two unknowns, two facts about them? Name the unknowns, turn each fact into an equation, solve the system, then sanity-check the answer against the story.$AMA$, $AMA$Linear System Applications (full lesson) | grade 10 math | jensenmath.ca$AMA$, $AMA$https://www.youtube.com/watch?v=Vr7l_5U7vQc$AMA$, $AMA$JensenMath$AMA$),
($AMA$MPM2D$AMA$, $AMA$Quadratics$AMA$, $AMA$sub-properties-of-quadratics$AMA$, 1, $AMA$Intro to Quadratic Relations$AMA$, $AMA$Throw a basketball. It doesn't go up in a straight line and stop — it curves up, peaks, then curves back down. That curve is a **parabola**, and the equation that describes it is a **quadratic relation**:$AMA$, 2, $AMA$# Intro to Quadratic Relations

## The Idea

Throw a basketball. It doesn't go up in a straight line and stop — it curves up, peaks, then curves back down. That curve is a **parabola**, and the equation that describes it is a **quadratic relation**:

```
y = ax² + bx + c   (a ≠ 0)
```

The `x²` is what makes it curve instead of going straight like `y = mx + b`.

## Spotting a Quadratic From a Table

If you make a table of x and y values with evenly spaced x's, look at how much y changes each step (the "first difference"), then how *that* changes (the "second difference"). If the second difference is constant, you're looking at a quadratic relation — guaranteed.

| x | y | 1st diff | 2nd diff |
|---|---|----------|----------|
| 0 | 1 |          |          |
| 1 | 2 | +1       |          |
| 2 | 5 | +3       | +2       |
| 3 | 10| +5       | +2       |

Constant +2 second difference → it's a parabola.

## Key Features of a Parabola

- **Vertex**: the highest or lowest point (the "tip" of the curve).
- **Axis of symmetry**: the vertical line through the vertex — the parabola is a mirror image on either side of it.
- **Zeros / x-intercepts**: where the curve crosses the x-axis (up to two of them).
- **y-intercept**: where the curve crosses the y-axis.
- **Maximum or minimum value**: the y-value of the vertex — a max if the parabola opens down, a min if it opens up.

:::img mpm2d-properties-of-quadratics_0
:::

:::desmos https://www.desmos.com/calculator/tmanhslyfn
:::

## Why It Matters

Quadratics show up anywhere something speeds up then slows down, or rises then falls — a ball's flight path, profit vs. price, the shape of a satellite dish. Recognizing the pattern early makes every later unit (transformations, factoring, the quadratic formula) click faster.

## Common Mistakes

- **Taking second differences from the wrong pair.** They come from
  subtracting *neighbouring* first differences: if the first differences run
  3, 5, 7, the second differences are `5 - 3` and `7 - 5`, both 2.
- **Reading the second difference as `a`.** A constant second difference
  equals **2a**, so a second difference of -6 means `a = -3`, not -6.
- **Letting `b` decide which way it opens.** Only the sign of `a` does that.
  `b` shifts the curve sideways, and the number of terms tells you nothing
  at all.
- **Confusing the y-intercept with the coefficient of x.** The y-intercept is
  the value when `x = 0`, which leaves only the constant on its own.
- **Thinking a bigger `a` means a wider curve.** Values bigger than 1 stretch
  it upward and pull it *narrower*. Wider comes from an `a` between 0 and 1.

## Quick Gut-Check

If a graph looks like a U or an upside-down U, and second differences in your table are constant, you're dealing with a quadratic relation.$AMA$, $AMA$Intro to Quadratics | math 10 | jensenmath.ca$AMA$, $AMA$https://www.youtube.com/watch?v=iz1US34cW9U$AMA$, $AMA$JensenMath$AMA$),
($AMA$MPM2D$AMA$, $AMA$Quadratics$AMA$, $AMA$sub-vertex-form$AMA$, 2, $AMA$Transformations of Quadratic Functions$AMA$, $AMA$Every parabola is really just `y = x²` that's been moved, flipped, or stretched. Once you know the "home base" shape of `y = x²`, you can sketch almost any parabola in seconds using vertex form:$AMA$, 1, $AMA$# Transformations of Quadratic Functions

## The Idea

Every parabola is really just `y = x²` that's been moved, flipped, or stretched. Once you know the "home base" shape of `y = x²`, you can sketch almost any parabola in seconds using vertex form:

```
y = a(x - h)² + k
```

## What Each Letter Does

- **h** — slides the graph **left/right**. Careful: it's `(x - h)`, so `y = (x - 3)²` moves *right* 3, and `y = (x + 3)²` moves *left* 3.
- **k** — slides the graph **up/down**. `y = x² + 4` moves up 4.
- **a** — controls the **shape**:
  - If `|a| > 1`, the parabola gets **narrower** (stretched vertically).
  - If `0 < |a| < 1`, it gets **wider** (compressed).
  - If `a` is **negative**, the parabola **flips upside down**.

## Reading Off the Vertex Instantly

In `y = a(x - h)² + k`, the vertex is simply **(h, k)** — no calculation needed. The axis of symmetry is the vertical line `x = h`.

## Worked Example

For `y = -2(x - 1)² + 5`:
- `a = -2` → flipped upside down, narrower than usual
- Vertex: `(1, 5)`
- Axis of symmetry: `x = 1`
- Since it opens downward, `y = 5` is the **maximum** value.

:::img mpm2d-vertex-form_0
:::

:::desmos https://www.desmos.com/calculator/vmvrgfuah9
:::

## Sketching Steps

1. Plot the vertex `(h, k)`.
2. Decide if it opens up (`a > 0`) or down (`a < 0`).
3. Use `a` to judge how narrow/wide it is compared to `y = x²`.
4. Mirror points across the axis of symmetry to finish the curve.

## Common Mistakes

- Mixing up the sign of `h` (remember: it's the *opposite* of what's in the brackets).
- Forgetting that a negative `a` flips the parabola, not just shrinks it.

## Quick Gut-Check

Vertex form basically hands you the vertex and shape for free — no graphing, no guesswork, just read `(h, k)` and the sign of `a`.$AMA$, $AMA$Quadratics in VERTEX FORM | math 10 | jensenmath.ca$AMA$, $AMA$https://www.youtube.com/watch?v=ajBJf1scjyY$AMA$, $AMA$JensenMath$AMA$),
($AMA$MPM2D$AMA$, $AMA$Quadratics$AMA$, $AMA$sub-completing-the-square$AMA$, 3, $AMA$Completing the Square$AMA$, $AMA$Not every quadratic factors nicely. Completing the square is a method that turns **any** quadratic from general form into vertex form, so you can find the vertex even when factoring won't work.$AMA$, 1, $AMA$# Completing the Square

## The Idea

Not every quadratic factors nicely. Completing the square is a method that turns **any** quadratic from general form into vertex form, so you can find the vertex even when factoring won't work.

```
y = ax² + bx + c   →   y = a(x - h)² + k
```

## The Steps (No Fractions Version)

Solve/convert `y = x² + 6x + 5`:

1. **Group** the x² and x terms: `y = (x² + 6x) + 5`
2. **Take half of the middle coefficient, square it**: half of 6 is 3, `3² = 9`
3. **Add and subtract that number inside**: `y = (x² + 6x + 9 - 9) + 5`
4. **Rewrite the perfect square trinomial as a bracket squared**: `y = (x + 3)² - 9 + 5`
5. **Simplify**: `y = (x + 3)² - 4`

Now you can read the vertex straight off: **(-3, -4)**

:::img mpm2d-completing-the-square_0
:::

:::desmos https://www.desmos.com/calculator/awahsolmh5
:::

## Worked Example (Leading Coefficient ≠ 1)

For `y = 3x² - 12x + 1`, first factor the 3 out of the x-terms only:
```
y = 3(x² - 4x) + 1
```
Half of -4 is -2, squared is 4:
```
y = 3(x² - 4x + 4 - 4) + 1
= 3(x - 2)² - 12 + 1
= 3(x - 2)² - 11
```
Vertex: **(2, -11)**

## Why Bother?

- It gets you the vertex without graphing.
- It's the method used to *derive* the quadratic formula.
- It works on quadratics that don't factor nicely with whole numbers.

## Common Mistakes

- Forgetting to multiply the subtracted number by `a` when there's a leading coefficient (see step with the 3 above — that -4 gets multiplied by 3 before combining with the +1).
- Adding the square number but forgetting to subtract it too — you can't just add something to one side without balancing it.

## Quick Gut-Check

Take half the x-coefficient, square it, add and subtract it inside the bracket — that's the whole trick.$AMA$, $AMA$Completing the square to write a quadratic in vertex form$AMA$, $AMA$https://www.youtube.com/watch?v=9YtUyWvTc0c$AMA$, $AMA$Joshua Helston$AMA$),
($AMA$MPM2D$AMA$, $AMA$Quadratics$AMA$, $AMA$sub-factored-form$AMA$, 4, $AMA$Graphing from Different Forms$AMA$, $AMA$A parabola can be written three different ways, and each form hands you a different shortcut for sketching it. Recognizing which form you have is the fastest way to graph a quadratic without a table of values.$AMA$, 6, $AMA$# Graphing from Different Forms

## The Idea

A parabola can be written three different ways, and each form hands you a different shortcut for sketching it. Recognizing which form you have — and what it gives you for free — is the fastest way to graph a quadratic without a table of values.

## The Three Forms

**Vertex form**: `y = a(x - h)² + k` → gives you the **vertex** `(h, k)` directly.

**Factored form**: `y = a(x - r)(x - s)` → gives you the **zeros** `x = r` and `x = s` directly.

**Standard form**: `y = ax² + bx + c` → gives you the **y-intercept** `(0, c)` directly.

:::img mpm2d-factored-form_0
:::

:::desmos https://www.desmos.com/calculator/vmvrgfuah9
:::

## Graphing from Vertex Form

For `y = 2(x - 3)² - 4`:
1. Plot the vertex: `(3, -4)`.
2. Since `a = 2 > 0`, it opens upward.
3. Pick one x-value near the vertex (say `x = 4`), find `y = 2(1)² - 4 = -2`, plot `(4, -2)`.
4. Mirror that point across the axis of symmetry `x = 3` to get `(2, -2)`.

## Graphing from Factored Form

For `y = -1(x - 1)(x - 5)`:
1. Plot the zeros: `(1, 0)` and `(5, 0)`.
2. The axis of symmetry is halfway between them: `x = 3`.
3. Substitute `x = 3` back in to find the vertex: `y = -1(2)(-2) = 4`, so the vertex is `(3, 4)`.
4. Since `a = -1 < 0`, it opens downward.

## Graphing from Standard Form

For `y = x² - 2x - 3`:
1. Plot the y-intercept: `(0, -3)`.
2. Find the axis of symmetry with `x = -b / (2a) = -(-2) / 2 = 1`.
3. Substitute `x = 1` to find the vertex: `y = 1 - 2 - 3 = -4`, so vertex is `(1, -4)`.
4. Use symmetry (or factor to `(x-3)(x+1)`) to find more points.

## Try It Yourself

Drag the sliders below to change `a`, `h`, and `k` in vertex form and watch the parabola move and reshape in real time.

## Converting Between Forms

You don't have to stay stuck in one form — expanding vertex/factored form gets you to standard form, and factoring/completing the square gets you back. Pick whichever form makes the graph you need easiest to see.

## Common Mistakes

- Forgetting the sign flip in vertex form: the vertex is `(h, k)`, not `(-h, k)`.
- Mixing up which form gives zeros vs. y-intercept.
- Not using the axis of symmetry to get a second point for free — every point has a matching mirror point.

## Quick Gut-Check

See vertex form → plot `(h, k)`. See factored form → plot the zeros and average them for the axis of symmetry. See standard form → plot `(0, c)` and use `x = -b/2a` for the axis of symmetry.$AMA$, $AMA$Graphing Quadratic Functions in Standard, Vertex, and Factored Form$AMA$, $AMA$https://www.youtube.com/watch?v=0NgJRegm-ZA$AMA$, $AMA$Mr. Allen Math$AMA$),
($AMA$MPM2D$AMA$, $AMA$Solving quadratic equations$AMA$, $AMA$sub-solving-by-factoring$AMA$, 1, $AMA$Solving Quadratic Equations by Factoring$AMA$, $AMA$To solve a quadratic equation, you need it to equal zero — then factor, and use one simple rule: if two things multiply to give zero, at least one of them **must** be zero.$AMA$, 1, $AMA$# Solving Quadratic Equations by Factoring

## The Idea

To solve a quadratic equation, you need it to equal zero — then factor, and use one simple rule: if two things multiply to give zero, at least one of them **must** be zero.

```
If (x - a)(x - b) = 0, then x = a or x = b
```

## The Steps

1. **Set the equation to zero** (move everything to one side).
2. **Factor** the expression completely.
3. **Set each bracket equal to zero** and solve.
4. **Check** both answers in the original equation.

## Worked Example

Solve `x² - x - 6 = 0`

Already equals zero. Factor:
```
(x - 3)(x + 2) = 0
```

Set each bracket to zero:
```
x - 3 = 0  →  x = 3
x + 2 = 0  →  x = -2
```

**Answer: x = 3 or x = -2**

Check: `(3)² - 3 - 6 = 9 - 3 - 6 = 0` ✓ and `(-2)² - (-2) - 6 = 4 + 2 - 6 = 0` ✓

## If It's Not Already Equal to Zero

Solve `x² + 4x = 5`. First move the 5 over:
```
x² + 4x - 5 = 0
(x + 5)(x - 1) = 0
x = -5 or x = 1
```

:::img mpm2d-solving-by-factoring_0
:::

:::desmos https://www.desmos.com/calculator/npqyjesssi
:::

## Why This Connects to Graphing

The solutions you find are exactly the **x-intercepts** (zeros) of the parabola `y = x² - x - 6`. Solving by factoring and finding zeros from a graph are the same thing, just from different directions.

## Common Mistakes

- Trying to solve before setting the equation to zero — the "multiply to zero" trick **only** works when one side is 0.
- Forgetting the second solution — quadratics usually have two answers, not one.

## Quick Gut-Check

See a quadratic set to zero and factorable? Split it into two brackets, solve each for zero, done.$AMA$, $AMA$Solving Quadratic Equations by FACTORING | Grade 10 Math | jensenmath.ca$AMA$, $AMA$https://www.youtube.com/watch?v=9w2XpdFxHHg$AMA$, $AMA$JensenMath$AMA$),
($AMA$MPM2D$AMA$, $AMA$Solving quadratic equations$AMA$, $AMA$sub-quadratic-formula$AMA$, 2, $AMA$The Quadratic Formula$AMA$, $AMA$When a quadratic won't factor nicely, the quadratic formula solves it every time. It works on **any** quadratic in the form `ax² + bx + c = 0`.$AMA$, 1, $AMA$# The Quadratic Formula

## The Idea

When a quadratic won't factor nicely, the quadratic formula solves it every time. It works on **any** quadratic in the form `ax² + bx + c = 0`.

```
x = (-b ± √(b² - 4ac)) / 2a
```

## The Steps

1. Write the equation in the form `ax² + bx + c = 0`.
2. Identify `a`, `b`, and `c`.
3. Plug them into the formula.
4. Simplify — you'll usually get **two answers**, one with `+` and one with `−`.

## Worked Example

Solve `2x² + 3x - 5 = 0`

Here: `a = 2`, `b = 3`, `c = -5`

```
x = (-3 ± √(3² - 4(2)(-5))) / 2(2)
x = (-3 ± √(9 + 40)) / 4
x = (-3 ± √49) / 4
x = (-3 ± 7) / 4
```

Two answers:
```
x = (-3 + 7)/4 = 1
x = (-3 - 7)/4 = -2.5
```

**Answer: x = 1 or x = -2.5**

## The Discriminant: A Sneak Peek at the Answer

The part under the square root, `b² - 4ac`, is called the **discriminant**. It tells you what kind of answers to expect before you even finish solving:

- **Positive** → two different real solutions
- **Zero** → exactly one real solution (the parabola just touches the x-axis)
- **Negative** → no real solutions (the parabola never touches the x-axis)

:::img mpm2d-quadratic-formula_0
:::

:::desmos https://www.desmos.com/calculator/cf5cvtow5t
:::

## Common Mistakes

- Forgetting the `±` — most quadratics have two solutions.
- Sign errors plugging in a negative `c` or `b` — write out the substitution fully before simplifying.
- Forgetting that the entire numerator, not just the square root part, gets divided by `2a`.

## Quick Gut-Check

Can't factor it easily? Grab `a`, `b`, `c`, plug into the formula, and let the arithmetic do the work.$AMA$, $AMA$Solving Equations with Quadratic Formula - Grade 10 Math, Ontario Curriculum$AMA$, $AMA$https://www.youtube.com/watch?v=F_gY8JmJktc$AMA$, $AMA$AllThingsMathematics$AMA$),
($AMA$MPM2D$AMA$, $AMA$Solving quadratic equations$AMA$, $AMA$sub-quadratic-applications$AMA$, 3, $AMA$Applications of Quadratic Equations$AMA$, $AMA$Quadratics aren't just abstract algebra — they model anything that rises then falls (or falls then rises): a ball's height over time, profit vs. price, the area of a fenced yard. These problems give you a real-world quadratic equation and ask questions about it.$AMA$, 2, $AMA$# Applications of Quadratic Equations

## The Idea

Quadratics aren't just abstract algebra — they model anything that rises then falls (or falls then rises): a ball's height over time, profit vs. price, the area of a fenced yard. These problems give you a real-world quadratic equation and ask questions about it.

## The Two Big Question Types

**1. "What's the maximum/minimum?"** → find the **vertex**.
**2. "When does it hit a certain value (like the ground)?"** → find the **zeros** (set the equation to 0 and solve, or set it equal to that value).

## Worked Example

A ball's height (in metres) over time (in seconds) is modelled by:
```
h = -5t² + 20t + 1
```

**Question A: What's the maximum height?**

Complete the square or use the vertex formula. Here `a = -5, b = 20`:
```
t = -b/2a = -20/(2(-5)) = 2
```
Sub back in: `h = -5(2)² + 20(2) + 1 = -20 + 40 + 1 = 21`

**Maximum height: 21 m, at t = 2 seconds**

**Question B: When does the ball hit the ground?**

The ground is `h = 0`:
```
-5t² + 20t + 1 = 0
```
Use the quadratic formula (this one doesn't factor nicely):
```
t = (-20 ± √(400 - 4(-5)(1))) / 2(-5)
t = (-20 ± √420) / -10
```
This gives `t ≈ -0.05` or `t ≈ 4.05`. Since time can't be negative, the ball hits the ground at **t ≈ 4.05 seconds**.

:::img mpm2d-quadratic-applications_0
:::

:::desmos https://www.desmos.com/calculator/ytuiidrwb5
:::

## Reading Word Problems

Look for these clues:
- "Maximum" or "minimum" → vertex question
- "When does it reach..." or "hits the ground/reaches zero" → set equation equal to that value and solve
- Always check if negative answers make sense in context (time, length, and price usually can't be negative)

## Common Mistakes

- Forgetting to reject answers that don't make physical sense (like negative time).
- Mixing up when to find the vertex vs. when to solve for zeros — read the question carefully.

## Quick Gut-Check

"How high/big/much" → vertex. "When/where does it happen" → solve for zero.$AMA$, $AMA$Applications of Quadratics | math 10 | jensenmath.ca$AMA$, $AMA$https://www.youtube.com/watch?v=iybyQZIp5_k$AMA$, $AMA$JensenMath$AMA$),
($AMA$MPM2D$AMA$, $AMA$Solving quadratic equations$AMA$, $AMA$sub-solving-by-completing-square$AMA$, 4, $AMA$Solving by Completing the Square$AMA$, $AMA$Completing the square turns any quadratic equation into a single squared bracket equal to a number, which you then finish with a square root and a plus-or-minus.$AMA$, 3, $AMA$# Solving by Completing the Square

## The Idea

`x² = 49` is easy to solve: square-root both sides and remember there are two answers, `x = ±7`. Completing the square is the manoeuvre that turns *any* quadratic equation into that shape — a single perfect square on one side and a plain number on the other — so you can finish with a square root instead of hunting for factors. It works whether or not the quadratic factors.

## The Method

To solve `ax² + bx + c = 0`:

- Move the constant to the right-hand side.
- If `a` is not 1, divide **every term on both sides** by `a`.
- Take half the coefficient of `x`, square it, and add that number to both sides.
- The left side is now a perfect square trinomial — write it as a squared bracket.
- Square-root both sides, keeping the `±`.
- Solve the two resulting one-step equations.

```
x² + px = q   →   (x + p/2)² = q + (p/2)²
```

## Worked Example

Solve `2x² + 12x - 6 = 0`.

- Move the constant: `2x² + 12x = 6`
- Divide every term by 2: `x² + 6x = 3`
- Half of 6 is 3, and `3² = 9`. Add 9 to both sides: `x² + 6x + 9 = 12`
- The left side is a perfect square: `(x + 3)² = 12`
- Square-root both sides: `x + 3 = ±√12`, and `√12 = 2√3`
- Isolate `x`: `x = -3 ± 2√3`

As decimals that is roughly `0.46` and `-6.46` — two answers, as a quadratic should have.

## Common Mistakes

- **Adding the new number to one side only.** From `x² + 6x = 3`, adding 9 on the left makes the right side 12, not 3. The equation has to stay balanced.
- **Dropping the `±`.** `(x + 3)² = 12` has two solutions, because both `2√3` and `-2√3` square to 12. Taking only the positive root quietly throws away a root every single time.
- **Dividing only the `x²` term by `a`.** `2x² + 12x = 6` becomes `x² + 6x = 3`; the `12x` and the `6` are divided too.
- **Squaring before halving.** For `x² + 6x`, the number to add is `(6 ÷ 2)² = 9`, not `6² ÷ 2 = 18`. Halve first, then square.
- **Getting the sign inside the bracket wrong.** For `x² - 8x`, half of `-8` is `-4`, so the square is `(x - 4)²`. Writing `(x + 4)²` expands to a middle term of `+8x`.
- **Stopping at `x + 3 = ±2√3`.** That is not an answer yet — the variable is still not alone.

## Quick Gut-Check

Coefficient of `x²` down to 1, constant across to the right, then half-and-square and add to both sides. If your final line has no `±` in it, you have lost a root.$AMA$, null, null, null),
($AMA$MPM2D$AMA$, $AMA$Solving quadratic equations$AMA$, $AMA$sub-standard-form-analysis$AMA$, 5, $AMA$Analysing a Quadratic in Standard Form$AMA$, $AMA$In y = ax² + bx + c, the coefficients tell you the direction, the y-intercept, the axis of symmetry and the number of x-intercepts without plotting anything.$AMA$, 3, $AMA$# Analysing a Quadratic in Standard Form

## The Idea

Standard form is `y = ax² + bx + c` — the form you end up with after expanding anything. It doesn't hand you the vertex the way vertex form does, but every coefficient in it is still telling you something you can read off the page without plotting a single point: which way the parabola opens, where it crosses the y-axis, where its mirror line sits, and how many times it meets the x-axis.

## What Each Coefficient Tells You

- **`a` — direction and width.** If `a > 0` the parabola opens up and the vertex is a **minimum**; if `a < 0` it opens down and the vertex is a **maximum**. The bigger `|a|` is, the narrower the curve.
- **`c` — the y-intercept.** Substituting `x = 0` wipes out the first two terms, so the curve always passes through `(0, c)`.
- **`a` and `b` together — the axis of symmetry:**

```
x = -b / (2a)
```

The vertex sits on that line, so substitute that `x` back into the equation to get the vertex's `y`-coordinate.

- **`b² - 4ac` — the number of x-intercepts.** Positive means two zeros, zero means exactly one (the vertex is sitting on the x-axis), negative means none at all.

:::img mpm2d-standard-form-analysis_0
:::caption Standard form hands you c as the height where the curve crosses the y-axis, -b/(2a) as the mirror line through the vertex, and b² - 4ac as the count of x-intercepts.
:::

## Worked Example

Analyse `y = -2x² + 8x - 5`.

- `a = -2` is negative, so the parabola opens **downward** and its vertex is a maximum.
- `c = -5`, so the y-intercept is `(0, -5)`.
- Axis of symmetry: `x = -8 / (2 × -2) = -8 / -4 = 2`.
- Vertex `y`: substitute `x = 2` → `-2(2)² + 8(2) - 5 = -8 + 16 - 5 = 3`. The vertex is `(2, 3)`, and the maximum value is 3.
- `b² - 4ac = 8² - 4(-2)(-5) = 64 - 40 = 24`, which is positive, so the parabola cuts the x-axis twice.

## Common Mistakes

- **Reading `c` as the vertex's height.** `c` is the value of `y` when `x = 0`. It only equals the vertex's `y` in the special case where the axis of symmetry happens to be `x = 0`.
- **Dropping the minus in `x = -b/(2a)`.** With `b = 8` and `a = -2` the answer is `2`, not `-2`. Substitute `b` with its own sign attached, then apply the leading minus to the whole fraction.
- **Dividing by 2 instead of `2a`.** The denominator is `2a`, so `a = -2` gives a denominator of `-4`, not 2.
- **Calling the axis of symmetry the vertex.** `x = 2` is a line, not a point. You only get the vertex `(2, 3)` after substituting back into the equation.
- **Sign slips in `b² - 4ac` when `a` and `c` are both negative.** `-4(-2)(-5)` is `-40`: three negatives multiplied give a negative. Writing `+40` turns a two-zero parabola into a no-zero one.
- **Thinking a negative discriminant means "no graph".** It only means the parabola never touches the x-axis. The curve is still there, sitting entirely above or entirely below the axis.

## Quick Gut-Check

Sign of `a` for the direction, `c` for the y-intercept, `-b/(2a)` for the mirror line, then substitute back for the vertex. Four facts, no graph paper needed.$AMA$, null, null, null),
($AMA$MPM2D$AMA$, $AMA$Trigonometry$AMA$, $AMA$sub-similar-triangles$AMA$, 1, $AMA$Similar Triangles$AMA$, $AMA$Two triangles are **similar** if they're the same shape but different sizes — like a photo and its zoomed-in copy. Their angles match exactly, and their sides all scale by the same factor.$AMA$, 1, $AMA$# Similar Triangles

## The Idea

Two triangles are **similar** if they're the same shape but different sizes — like a photo and its zoomed-in copy. Their angles match exactly, and their sides all scale by the same factor.

## Similar vs. Congruent

- **Congruent**: identical in shape AND size (you could stack them exactly on top of each other).
- **Similar**: identical shape, but scaled up or down — angles match, sides are proportional.

Every congruent pair is also similar (with a scale factor of 1), but not every similar pair is congruent.

## How to Confirm Triangles Are Similar

- All corresponding **angles are equal**
- All corresponding **sides are in the same ratio** (proportional)

You typically only need to check angles (if two angles match, the third automatically matches too, since angles in a triangle add to 180°).

## Worked Example

Triangle ABC has sides 3, 4, 5. Triangle DEF has sides 6, 8, 10. Are they similar?

Check the ratios:
```
6/3 = 2
8/4 = 2
10/5 = 2
```

All ratios equal 2 — the triangles are **similar**, with a scale factor of 2.

:::img mpm2d-similar-triangles_0
:::

:::desmos https://www.desmos.com/calculator/tupqgluave
:::

## Using Similarity to Find Missing Values

If triangle ABC ~ triangle DEF with a scale factor of 2, and side AB = 5, then side DE = 5 × 2 = 10. Set up a proportion and cross-multiply if the scale factor isn't obvious.

## Real-World Uses

- Measuring the height of a tall object using its shadow and a known-height object's shadow
- Scale models and blueprints
- Reflections in mirrors or water

## Common Mistakes

- Matching up the wrong corresponding sides/angles — label triangles carefully in the same order (A↔D, B↔E, C↔F).
- Assuming triangles are similar just because they "look" similar — always verify with angles or side ratios.

## Quick Gut-Check

Same shape, different size, all side ratios equal → similar triangles.$AMA$, $AMA$7.1/7.2 Similar Triangles (Grade 10 Academic, MPM2D)$AMA$, $AMA$https://www.youtube.com/watch?v=1uycI1ahVRk$AMA$, $AMA$Mr. Cioffi$AMA$),
($AMA$MPM2D$AMA$, $AMA$Trigonometry$AMA$, $AMA$sub-trig-ratios$AMA$, 2, $AMA$Primary Trig Ratios (SOH CAH TOA)$AMA$, $AMA$In any right triangle, the ratios between its sides depend only on the angle — not the size of the triangle. That constant relationship is what sine, cosine, and tangent measure, and it lets you find missing sides or angles without ever drawing to scale.$AMA$, 2, $AMA$# Primary Trig Ratios (SOH CAH TOA)

## The Idea

In any right triangle, the ratios between its sides depend only on the angle — not the size of the triangle. That constant relationship is what sine, cosine, and tangent measure, and it lets you find missing sides or angles without ever drawing to scale.

## Naming the Sides (Relative to Your Angle)

- **Hypotenuse**: always the longest side, opposite the right angle.
- **Opposite**: the side across from the angle you're working with.
- **Adjacent**: the side next to the angle (that isn't the hypotenuse).

## The Formulas: SOH CAH TOA

```
sin(angle) = Opposite / Hypotenuse
cos(angle) = Adjacent / Hypotenuse
tan(angle) = Opposite / Adjacent
```

## Worked Example: Finding a Side

A right triangle has a 30° angle and a hypotenuse of 10. Find the opposite side.

Opposite and hypotenuse involved → use **sine**:
```
sin(30°) = opposite / 10
opposite = 10 × sin(30°)
opposite = 10 × 0.5 = 5
```

:::img mpm2d-trig-ratios_0
:::

:::desmos https://www.desmos.com/calculator/kbkffchpfg
:::

## Worked Example: Finding an Angle

A right triangle has an opposite side of 7 and adjacent side of 4. Find the angle.

Opposite and adjacent → use **tangent**, then undo it with inverse tangent:
```
tan(θ) = 7/4
θ = tan⁻¹(7/4) ≈ 60.3°
```

## Don't Forget the Pythagorean Theorem

If you have two sides and need the third (no angle needed), skip trig entirely:
```
a² + b² = c²   (c = hypotenuse)
```

## Choosing the Right Tool

1. Label the triangle: hypotenuse, opposite, adjacent (relative to your known/target angle).
2. Decide what you know and what you need.
3. Pick SOH, CAH, or TOA based on which two sides (or side + angle) are involved.
4. If no angle is involved at all, use Pythagorean theorem instead.

## Common Mistakes

- Mislabeling opposite vs. adjacent — they depend on *which angle* you're using, not fixed positions.
- Forgetting to use the inverse function (sin⁻¹, cos⁻¹, tan⁻¹) when solving for an angle instead of a side.

## Quick Gut-Check

Identify which two sides (or side and angle) you're working with, then match them to SOH, CAH, or TOA.$AMA$, $AMA$Basic trigonometry | Trigonometry | Khan Academy$AMA$, $AMA$https://www.youtube.com/watch?v=Jsiy4TxgIME$AMA$, $AMA$Khan Academy$AMA$),
($AMA$MPM2D$AMA$, $AMA$Trigonometry$AMA$, $AMA$sub-sine-law$AMA$, 3, $AMA$The Sine Law$AMA$, $AMA$SOH CAH TOA only works on right triangles. For triangles **without** a right angle (acute or obtuse), the sine law connects each side to the sine of its opposite angle — and that ratio is the same all the way around the triangle.$AMA$, 1, $AMA$# The Sine Law

## The Idea

SOH CAH TOA only works on right triangles. For triangles **without** a right angle (acute or obtuse), the sine law connects each side to the sine of its opposite angle — and that ratio is the same all the way around the triangle.

```
a/sin(A) = b/sin(B) = c/sin(C)
```

(Each lowercase side is opposite the matching uppercase angle.)

## When to Use It

Use the sine law when you know **an angle and its opposite side**, plus one more piece of information (another angle, or another side).

## Worked Example: Finding a Side

Triangle with angle A = 40°, angle B = 60°, and side a = 8. Find side b.

```
8/sin(40°) = b/sin(60°)
b = sin(60°) × 8/sin(40°)
b = 0.866 × 8/0.643
b ≈ 10.8
```

:::img mpm2d-sine-law_0
:::

:::desmos https://www.desmos.com/calculator/hwqy8wrxpz
:::

## Worked Example: Finding an Angle

Triangle with side a = 10, side b = 7, and angle A = 50°. Find angle B.

```
10/sin(50°) = 7/sin(B)
sin(B) = 7 × sin(50°)/10
sin(B) = 7 × 0.766/10 = 0.536
B = sin⁻¹(0.536) ≈ 32.4°
```

## Setting It Up Correctly

Only use two ratios at a time (not all three at once) — pick the pair where you know three of the four values, and solve for the fourth.

## Common Mistakes

- Mismatching a side with the wrong angle — always pair a side with the angle **directly opposite** it.
- Forgetting that side/sine ratios must use the *same* units and same triangle labelling throughout.
- Not checking whether the sine law is even the right tool — if you know two sides and the angle **between** them (not opposite either), you need the cosine law instead.

## Quick Gut-Check

Know an angle-side opposite pair, plus one more angle or side? Use the sine law.$AMA$, $AMA$Sine Law | Grade 10 Math | jensenmath.ca$AMA$, $AMA$https://www.youtube.com/watch?v=KQ5j4Tl_mWA$AMA$, $AMA$JensenMath$AMA$),
($AMA$MPM2D$AMA$, $AMA$Trigonometry$AMA$, $AMA$sub-cosine-law$AMA$, 4, $AMA$The Cosine Law$AMA$, $AMA$The cosine law is a backup for the sine law — it handles cases where you **don't** have an angle-side opposite pair to work with. It's basically the Pythagorean theorem with an extra correction term for triangles that aren't right triangles.$AMA$, 2, $AMA$# The Cosine Law

## The Idea

The cosine law is a backup for the sine law — it handles cases where you **don't** have an angle-side opposite pair to work with. It's basically the Pythagorean theorem with an extra correction term for triangles that aren't right triangles.

```
c² = a² + b² - 2ab·cos(C)
```

(where C is the angle between sides a and b, and c is the side opposite that angle)

## When to Use It

- **Two sides + the angle between them** → find the third side.
- **All three sides, no angles** → find any angle (rearrange the formula).

## Worked Example: Finding a Side

Sides a = 7, b = 9, and the angle between them C = 50°. Find side c.

```
c² = 7² + 9² - 2(7)(9)cos(50°)
c² = 49 + 81 - 126(0.643)
c² = 130 - 81
c² ≈ 49
c ≈ 7
```

:::img mpm2d-cosine-law_0
:::

:::desmos https://www.desmos.com/calculator/pzsikmcx87
:::

## Worked Example: Finding an Angle

All three sides known: a = 6, b = 8, c = 10. Find angle C (opposite side c).

Rearranged formula:
```
cos(C) = (a² + b² - c²) / 2ab
cos(C) = (36 + 64 - 100) / (2×6×8)
cos(C) = 0/96 = 0
C = cos⁻¹(0) = 90°
```

(This confirms it's actually a right triangle — the cosine law includes Pythagorean theorem as a special case!)

## Sine Law vs. Cosine Law: Which One?

| You know | Use |
|---|---|
| An angle and its opposite side, plus one more piece | Sine Law |
| Two sides and the angle between them | Cosine Law |
| All three sides, no angles | Cosine Law (rearranged) |

## Common Mistakes

- Using the cosine law when the sine law would be simpler (and vice versa) — check what you're given first.
- Forgetting to rearrange the formula correctly when solving for an angle instead of a side.
- Calculator angle mode errors — make sure it's set to degrees (or radians) as required by the problem.

## Quick Gut-Check

No opposite angle-side pair available? Two sides and the angle between them, or all three sides? That's cosine law territory.$AMA$, $AMA$Cosine Law | grade 10 math | jensenmath.ca$AMA$, $AMA$https://www.youtube.com/watch?v=-2wLuC6qY58$AMA$, $AMA$JensenMath$AMA$),
($AMA$MPM2D$AMA$, $AMA$Trigonometry$AMA$, $AMA$sub-trig-side-lengths$AMA$, 5, $AMA$Angle of Elevation & Depression$AMA$, $AMA$These are just primary trig ratios wearing a real-world costume — the angle you look up or down through, measured from the horizontal, to see something above or below you.$AMA$, 6, $AMA$# Angle of Elevation & Depression

## The Idea

These are just primary trig ratios wearing a real-world costume. The **angle of elevation** is the angle you look UP through, from the horizontal, to see something above you. The **angle of depression** is the angle you look DOWN through, from the horizontal, to see something below you.

## The Key Insight

Both angles are always measured from a **horizontal line**, never from the ground or a wall directly. Once you spot the horizontal line and the line of sight, you have a right triangle — and SOH CAH TOA takes it from there.

## Try It Yourself

Drag the slider to change the angle of elevation and watch the height and distance relationship update.

## Angle of Elevation

Standing 50 m from the base of a tower, you look up at its top with an angle of elevation of 35°. How tall is the tower?

The horizontal distance (50 m) is **adjacent** to the angle, and the height is **opposite**:
```
tan(35°) = opposite / adjacent = height / 50
height = 50 × tan(35°) ≈ 35.0 m
```

## Angle of Depression

From the top of a 40 m cliff, you spot a boat with an angle of depression of 20°. How far is the boat from the base of the cliff?

Here's the trick: the angle of depression from the top equals the angle of elevation from the boat's point of view (alternate angles, parallel horizontal lines). The height (40 m) is **opposite**, the distance is **adjacent**:
```
tan(20°) = opposite / adjacent = 40 / distance
distance = 40 / tan(20°) ≈ 109.9 m
```

:::img mpm2d-trig-side-lengths_0
:::

:::desmos https://www.desmos.com/calculator/j2ox7rhgvo
:::

## Common Mistakes

- Measuring the angle from the ground/vertical instead of the horizontal — always double check which line the angle is drawn from.
- Mixing up which side is opposite vs. adjacent once the triangle is tilted at an angle.
- Forgetting that angle of elevation (looking up) equals angle of depression (looking down) for the SAME line of sight.

## Quick Gut-Check

Draw the horizontal line first. The angle between it and your line of sight is the angle of elevation or depression. Label opposite/adjacent relative to THAT angle, then apply SOH CAH TOA as usual.$AMA$, $AMA$Angle of Elevation and Depression Word Problems Trigonometry, Finding Sides, Angles, Right Triangles$AMA$, $AMA$https://www.youtube.com/watch?v=uyKvSe6Ltgs$AMA$, $AMA$The Organic Chemistry Tutor$AMA$),
($AMA$MPM2D$AMA$, $AMA$Trigonometry$AMA$, $AMA$sub-trig-angles$AMA$, 6, $AMA$Applications of Acute Triangle Trig$AMA$, $AMA$Real problems rarely announce whether to use the sine law or cosine law — you have to read the given information and decide. Multi-step problems often need both laws in sequence.$AMA$, 8, $AMA$# Applications of Acute Triangle Trig

## The Idea

Real problems rarely announce whether to use the sine law or cosine law — you have to read the given information and decide. Multi-step problems often need BOTH laws in sequence: find one missing piece with one law, then use it to find the next piece with the other.

## Choosing Your Law

**Sine Law** — use when you know:
- Two angles and any side (AAS or ASA), or
- Two sides and an angle opposite one of them (SSA)

```
a/sin(A) = b/sin(B) = c/sin(C)
```

**Cosine Law** — use when you know:
- All three sides (SSS), or
- Two sides and the angle between them (SAS)

```
a² = b² + c² - 2bc·cos(A)
```

## Worked Example: Two Steps, Two Laws

A surveyor stands at point `A`. A tower `B` is 250 m away, and a second tower `C` is 180 m away. The angle at `A` between the two towers is 65°. Find the distance between the towers, and the angle at `B`.

**Step 1 — find `BC` using the cosine law** (SAS: two sides and the included angle):
```
BC² = 250² + 180² - 2(250)(180)cos(65°)
BC² = 62500 + 32400 - 90000(0.4226)
BC² ≈ 56920
BC ≈ 238.6 m
```

**Step 2 — find angle `B` using the sine law**:
```
sin(B)/180 = sin(65°)/238.6
sin(B) = 180 × sin(65°) / 238.6 ≈ 0.6842
B ≈ 43.2°
```

:::img mpm2d-trig-angles_0
:::

:::desmos https://www.desmos.com/calculator/mzzhuovuwd
:::

## Worked Example: Navigation Problem

A ship sails from port on a bearing that takes it 40 km, then turns and sails 55 km on a bearing that creates a 110° angle with its first path. How far is the ship from port?

This is SAS — two sides (40 km, 55 km) and the included angle (110°) — straight to the cosine law:
```
d² = 40² + 55² - 2(40)(55)cos(110°)
d² = 1600 + 3025 - 4400(-0.342)
d² ≈ 6130.4
d ≈ 78.3 km
```

## A Decision Checklist

1. Draw and label the triangle with everything you know.
2. Count what you have: 3 sides? 2 sides + included angle? → cosine law. 2 angles + a side, or 2 sides + a non-included angle? → sine law.
3. Solve for the missing piece.
4. If the problem needs another unknown, repeat — you may switch laws partway through.

## Common Mistakes

- Reaching for the sine law when you only have two sides and the angle between them — that's cosine law territory.
- Rounding intermediate answers too early, which compounds error through a multi-step problem — keep extra decimal places until the final answer.
- Forgetting to check for the ambiguous case (SSA) — two triangles can sometimes fit the same given information.

## Quick Gut-Check

All sides or two-sides-plus-included-angle → cosine law. Anything with a full angle-side pair known → sine law. Multi-step problems often use one law to unlock the information the other law needs.$AMA$, $AMA$Trigonometry Problems in 2 and 3 Dimensions (full lesson) | jensenmath.ca$AMA$, $AMA$https://www.youtube.com/watch?v=RoMMs_Zg3nM$AMA$, $AMA$JensenMath$AMA$);
