-- ======================================================================
-- figures_mdm4u.sql — attaches figures to questions
-- ======================================================================
-- GENERATED by tools/make_figures.py — edit that script, not this file.
--
-- Run AFTER the question files for this course, and after any re-run of
-- one: the per-unit delete wipes the figure column with the rest of the
-- row. Safe to re-run on its own at any time.
--
-- The PNGs live in web/figures/ and ship inside every deploy. A null
-- figure renders no image, and a missing file shows a short "could not
-- load" line in the app rather than a broken icon.

update questions set figure = null where course_code = 'MDM4U';

update questions set figure = 'figures/mdm4u_stat_10.png'
 where course_code = 'MDM4U' and unit = 'Displays of Data' and sort_order = 10;
update questions set figure = 'figures/mdm4u_stat_17.png'
 where course_code = 'MDM4U' and unit = 'Displays of Data' and sort_order = 17;
update questions set figure = 'figures/mdm4u_stat_25.png'
 where course_code = 'MDM4U' and unit = 'Normal Distributions' and sort_order = 25;
update questions set figure = 'figures/mdm4u_venn_14.png'
 where course_code = 'MDM4U' and unit = 'Probability' and sort_order = 14;
update questions set figure = 'figures/mdm4u_geo_21.png'
 where course_code = 'MDM4U' and unit = 'Probability Distributions' and sort_order = 21;

-- Check: every figure attached, and none orphaned.
select unit, sort_order, figure from questions
 where course_code = 'MDM4U' and figure is not null
 order by unit, sort_order;
