-- ======================================================================
-- figures_mcr3u.sql — attaches figures to questions
-- ======================================================================
-- GENERATED by tools/make_figures.py — edit that script, not this file.
--
-- Run AFTER the question files for this course, and after any re-run of
-- one: the per-unit delete wipes the figure column with the rest of the
-- row. Safe to re-run on its own at any time.
--
-- The PNGs live in web/figures/ and ship inside every deploy. A null
-- figure renders no image, and a missing file shows a short "could not
-- load" line in the app rather than a broken icon.

update questions set figure = null where course_code = 'MCR3U';

update questions set figure = 'figures/mcr3u_trig_9.png'
 where course_code = 'MCR3U' and unit = 'Trig Geometry' and sort_order = 9;
update questions set figure = 'figures/mcr3u_trig_19.png'
 where course_code = 'MCR3U' and unit = 'Trig Geometry' and sort_order = 19;
update questions set figure = 'figures/mcr3u_trig_26.png'
 where course_code = 'MCR3U' and unit = 'Trig Geometry' and sort_order = 26;
update questions set figure = 'figures/mcr3u_trig_27.png'
 where course_code = 'MCR3U' and unit = 'Trig Geometry' and sort_order = 27;
update questions set figure = 'figures/mcr3u_trig_38.png'
 where course_code = 'MCR3U' and unit = 'Trig Geometry' and sort_order = 38;
update questions set figure = 'figures/mcr3u_trig_29.png'
 where course_code = 'MCR3U' and unit = 'Trig Functions' and sort_order = 29;
update questions set figure = 'figures/mcr3u_trig_39.png'
 where course_code = 'MCR3U' and unit = 'Trig Functions' and sort_order = 39;
update questions set figure = 'figures/mcr3u_disc_20.png'
 where course_code = 'MCR3U' and unit = 'Discrete Functions' and sort_order = 20;

-- Check: every figure attached, and none orphaned.
select unit, sort_order, figure from questions
 where course_code = 'MCR3U' and figure is not null
 order by unit, sort_order;
