-- ======================================================================
-- figures_mhf4u.sql — attaches figures to questions
-- ======================================================================
-- GENERATED by tools/make_figures.py — edit that script, not this file.
--
-- Run AFTER the question files for this course, and after any re-run of
-- one: the per-unit delete wipes the figure column with the rest of the
-- row. Safe to re-run on its own at any time.
--
-- The PNGs live in web/figures/ and ship inside every deploy. A null
-- figure renders no image, and a missing file shows a short "could not
-- load" line in the app rather than a broken icon.

update questions set figure = null where course_code = 'MHF4U';

update questions set figure = 'figures/mhf4u_trig_20.png'
 where course_code = 'MHF4U' and unit = 'Trig in Radians' and sort_order = 20;
update questions set figure = 'figures/mhf4u_trig_31.png'
 where course_code = 'MHF4U' and unit = 'Trig Identities and Equations' and sort_order = 31;

-- Check: every figure attached, and none orphaned.
select unit, sort_order, figure from questions
 where course_code = 'MHF4U' and figure is not null
 order by unit, sort_order;
