-- ======================================================================
-- figures_mcv4u.sql — attaches figures to questions
-- ======================================================================
-- GENERATED by tools/make_figures.py — edit that script, not this file.
--
-- Run AFTER the question files for this course, and after any re-run of
-- one: the per-unit delete wipes the figure column with the rest of the
-- row. Safe to re-run on its own at any time.
--
-- The PNGs live in web/figures/ and ship inside every deploy. A null
-- figure renders no image, and a missing file shows a short "could not
-- load" line in the app rather than a broken icon.

update questions set figure = null where course_code = 'MCV4U';

update questions set figure = 'figures/mcv4u_motion_29.png'
 where course_code = 'MCV4U' and unit = 'Derivative Rules' and sort_order = 29;
update questions set figure = 'figures/mcv4u_extrema_08.png'
 where course_code = 'MCV4U' and unit = 'Curve Sketching' and sort_order = 8;
update questions set figure = 'figures/mcv4u_optim_10.png'
 where course_code = 'MCV4U' and unit = 'Curve Sketching' and sort_order = 10;
update questions set figure = 'figures/mcv4u_deriv_18.png'
 where course_code = 'MCV4U' and unit = 'Curve Sketching' and sort_order = 18;
update questions set figure = 'figures/mcv4u_vect_06.png'
 where course_code = 'MCV4U' and unit = 'Geometric Vectors' and sort_order = 6;
update questions set figure = 'figures/mcv4u_vect_13.png'
 where course_code = 'MCV4U' and unit = 'Geometric Vectors' and sort_order = 13;
update questions set figure = 'figures/mcv4u_vect_27.png'
 where course_code = 'MCV4U' and unit = 'Geometric Vectors' and sort_order = 27;
update questions set figure = 'figures/mcv4u_vect_39.png'
 where course_code = 'MCV4U' and unit = 'Geometric Vectors' and sort_order = 39;
update questions set figure = 'figures/mcv4u_vect_25.png'
 where course_code = 'MCV4U' and unit = 'Algebraic Vectors' and sort_order = 25;
update questions set figure = 'figures/mcv4u_vect_28.png'
 where course_code = 'MCV4U' and unit = 'Algebraic Vectors' and sort_order = 28;
update questions set figure = 'figures/mcv4u_vect_39b.png'
 where course_code = 'MCV4U' and unit = 'Algebraic Vectors' and sort_order = 39;
update questions set figure = 'figures/mcv4u_line_01.png'
 where course_code = 'MCV4U' and unit = 'Lines and Planes' and sort_order = 1;

-- Check: every figure attached, and none orphaned.
select unit, sort_order, figure from questions
 where course_code = 'MCV4U' and figure is not null
 order by unit, sort_order;
