-- ======================================================================
-- figures_grade10.sql — attaches figures to questions
-- ======================================================================
-- GENERATED by tools/make_figures.py — edit that script, not this file.
--
-- Run AFTER questions_grade10.sql (the questions must exist), and after
-- any re-run of it: the per-unit delete wipes the figure column with the
-- rest of the row. Safe to re-run on its own at any time.
--
-- The PNGs live in web/figures/ and ship inside every deploy. A null
-- figure renders no image, and a missing file shows a short "could not
-- load" line in the app rather than a broken icon.

update questions set figure = null where grade = 10;

update questions set figure = 'figures/trig_13.png'
 where grade = 10 and unit = 'Trigonometry' and sort_order = 13;
update questions set figure = 'figures/trig_14.png'
 where grade = 10 and unit = 'Trigonometry' and sort_order = 14;
update questions set figure = 'figures/trig_21.png'
 where grade = 10 and unit = 'Trigonometry' and sort_order = 21;
update questions set figure = 'figures/trig_22.png'
 where grade = 10 and unit = 'Trigonometry' and sort_order = 22;
update questions set figure = 'figures/trig_29.png'
 where grade = 10 and unit = 'Trigonometry' and sort_order = 29;
update questions set figure = 'figures/trig_31.png'
 where grade = 10 and unit = 'Trigonometry' and sort_order = 31;
update questions set figure = 'figures/trig_34.png'
 where grade = 10 and unit = 'Trigonometry' and sort_order = 34;
update questions set figure = 'figures/trig_36.png'
 where grade = 10 and unit = 'Trigonometry' and sort_order = 36;
update questions set figure = 'figures/trig_40.png'
 where grade = 10 and unit = 'Trigonometry' and sort_order = 40;
update questions set figure = 'figures/sqe_40.png'
 where grade = 10 and unit = 'Solving quadratic equations' and sort_order = 40;
update questions set figure = 'figures/sqe_29.png'
 where grade = 10 and unit = 'Solving quadratic equations' and sort_order = 29;
update questions set figure = 'figures/sqe_31.png'
 where grade = 10 and unit = 'Solving quadratic equations' and sort_order = 31;
update questions set figure = 'figures/sqe_36.png'
 where grade = 10 and unit = 'Solving quadratic equations' and sort_order = 36;
update questions set figure = 'figures/trig_2.png'
 where grade = 10 and unit = 'Trigonometry' and sort_order = 2;
update questions set figure = 'figures/trig_11.png'
 where grade = 10 and unit = 'Trigonometry' and sort_order = 11;
update questions set figure = 'figures/trig_6.png'
 where grade = 10 and unit = 'Trigonometry' and sort_order = 6;
update questions set figure = 'figures/trig_8.png'
 where grade = 10 and unit = 'Trigonometry' and sort_order = 8;
update questions set figure = 'figures/trig_15.png'
 where grade = 10 and unit = 'Trigonometry' and sort_order = 15;
update questions set figure = 'figures/trig_16.png'
 where grade = 10 and unit = 'Trigonometry' and sort_order = 16;
update questions set figure = 'figures/trig_17.png'
 where grade = 10 and unit = 'Trigonometry' and sort_order = 17;
update questions set figure = 'figures/trig_23.png'
 where grade = 10 and unit = 'Trigonometry' and sort_order = 23;
update questions set figure = 'figures/trig_28.png'
 where grade = 10 and unit = 'Trigonometry' and sort_order = 28;
update questions set figure = 'figures/trig_37.png'
 where grade = 10 and unit = 'Trigonometry' and sort_order = 37;
update questions set figure = 'figures/trig_18.png'
 where grade = 10 and unit = 'Trigonometry' and sort_order = 18;
update questions set figure = 'figures/trig_19.png'
 where grade = 10 and unit = 'Trigonometry' and sort_order = 19;
update questions set figure = 'figures/trig_20.png'
 where grade = 10 and unit = 'Trigonometry' and sort_order = 20;
update questions set figure = 'figures/trig_24.png'
 where grade = 10 and unit = 'Trigonometry' and sort_order = 24;
update questions set figure = 'figures/trig_25.png'
 where grade = 10 and unit = 'Trigonometry' and sort_order = 25;
update questions set figure = 'figures/trig_26.png'
 where grade = 10 and unit = 'Trigonometry' and sort_order = 26;
update questions set figure = 'figures/trig_32.png'
 where grade = 10 and unit = 'Trigonometry' and sort_order = 32;
update questions set figure = 'figures/trig_33.png'
 where grade = 10 and unit = 'Trigonometry' and sort_order = 33;
update questions set figure = 'figures/trig_38.png'
 where grade = 10 and unit = 'Trigonometry' and sort_order = 38;
update questions set figure = 'figures/ag_27.png'
 where grade = 10 and unit = 'Analytic geometry' and sort_order = 27;

-- Check: every figure attached, and none orphaned.
select unit, sort_order, figure from questions
 where grade = 10 and figure is not null
 order by unit, sort_order;
